### PR TITLE
Migrate USB, thermal QTI HAL to AIDL

### PR DESCRIPTION
**Pull request by EndCredits**
Follow [topic: lineage-22.0-legacy-um - LineageOS Gerrit](https://review.lineageos.org/q/project:LineageOS/android_device_qcom_sepolicy_vndr+branch:lineage-22.0-legacy-um) , and maybe we should do the same for device side HALs

### CODE REVIEW

**Comment by NurKeinNeid** [comment]
Yes, I planned it already. Just wanted to wait until Lineage is done. And I dont do such big changes during work week because of less time.

**Comment by EndCredits** [comment]
> Yes, I planned it already. Just wanted to wait until Lineage is done. And I dont do such big changes during work week because of less time.

I'm testing the two AIDL now, if works fine I'll pr them for you so you can take a break. Don't push yourself. Winter is coming, please keep warm ~

**Comment by NurKeinNeid** [comment]
Thank you very much!

**Comment by NurKeinNeid** [comment]
Done

**Pull request closed without merging**
